export const state = {
  running: false,
  layerCount: 0,
  candidateLayer: 0,
  candidateSince: 0,
  stopCooldownUntil: 0,
  stopGesture: {
    phase: "idle",
    handedness: null,
    startWidth: 0,
    armedAt: 0,
    farAt: 0,
  },
  hands: [],
  lastHands: [],
  rawHands: 0,
  masterVolume: 0.72,
  targetVolume: 0.72,
  scratchEnergy: 0,
  scratchPhase: 0,
  boostEnergy: 0,
  handEnergy: 0,
  gestureBeat: 0,
  stageControl: {
    active: false,
    candidateSince: 0,
    lastActiveAt: 0,
    spread: 0,
    depth: 0,
    twist: 0,
    lift: 0,
    centerX: 0,
    centerY: 0,
    energy: 0,
  },
  model: {
    loading: false,
    loaded: false,
    error: "",
    progress: 0,
    progressLabel: "MODEL 0%",
    summon: 0,
    editor: {
      enabled: false,
      scale: 1.45,
      x: 0,
      y: -0.92,
      z: -0.7,
      rotY: 0,
      rotZ: 0,
      cameraZ: 7.6,
    },
    debug: {
      visible: false,
      scale: 0,
      x: 0,
      y: 0,
      z: 0,
      rotY: 0,
      rotZ: 0,
      cameraZ: 8,
    },
  },
  indexLink: null,
  indexLinkUntil: 0,
  fps: 0,
  modelReady: false,
  lastGestureAt: 0,
  faceDetected: false,
  faceLandmarks: [],
  faceBounds: null,
  glassesEnabled: false,
  glassesAnchor: {
    detected: false,
    center: { x: 0.5, y: 0.38, z: 0 },
    left: { x: 0.43, y: 0.38, z: 0 },
    right: { x: 0.57, y: 0.38, z: 0 },
    width: 0.24,
    height: 0.07,
    angle: 0,
  },
};
